# GAAP Features Report July 2023 
**This report details GAAP data collection efforts through 07/17/2023.** 

## Executive Summary

The GAAP Features source code library processes all raw SEC 10-Q filing document collections extracting the filing's XBRL instance document and all XBRL facts disclosed by the filer. The XBRL instance document typically references multiple taxonomies such as the US-GAAP taxonomy that define the numerous individual XBRL facts contained within the instance document.  Each fact typically contains one piece of digital data (the value) and all of the associated metadata (name, data type, decimal places, debit / credit, USD, shares, ratio, text block, labels, taxonomy url, namespace etc) that define the fact's value. One fact can contain any number of metadata elements defined in its taxonomy definition.  One filing may reference the US-GAAP taxonomy and any other number of other taxonomies containing fact specific definitions.

SEC filings use XBRL facts to disclose filing metadata, report text blocks, fiscal duration data, fiscal instance data, share data, ratio data, filing flags, and other filing specific information. The GAAP Features library processes XBRL facts and uses the filing specific metadata to organize and create filing and fact specific views for all of the data disclosed.

Fiscal instance and duration data contain all financial assets, income, cash flows, and balance sheet data included within each filing. The library uses both instance and duration data to identify common accounting periods and financial disclosures contained within 10-Q filings such as: quarter over quarter, year over year, YTD over YTD, document / fiscal period ending, and fiscal year ending financial performance results.  

Once fiscal instance and duration records are categorized and matched, percentage changes may also be determined for financial performance elements disclosed across multiple fiscal instances or durations.  For example, two fiscal durations make up the current quarterly results (duration 1) for a filer and the same period for the prior year (duration 2).  Percentage changes for any XRBL fact disclosed in both fiscal durations, such as gross income, can be determined.  

The current library calculates percentage changes for all financial items disclosed in Year over Year quarterly durations (QoQ), fiscal YTD over YTD durations (YoY), and the fiscal year end instant over document period ending instant (FYED to DPED).    

## Library Functionality and Coverages
The remainder of this report shows detailed examples and explanations for each data view extracted from a sample filing.  In addition, coverages are provided for each type of filing view collected.  

**Total Filings collected since 2019** 
* Count: 81953

**XBRL Instance Documents Extracted** 
* Count: 79733 
* Coverage: 97.29% 
* Most (if not all) of the missing files are from filings that did not submit an XBRL instance document. 

**GAAP Feature Files** 
* Count: 79733 
* Coverage: 97.29% 

**GAAP Metadata**  
* Count: 79733 
* Coverage: 97.29% 

**Filings with Fiscal Durations**
* Count: 79733 
* Coverage: 97.29% 

**Filings with >=2 Fiscal Durations**
* Count: 79341 
* Coverage: 96.81% 

**Filings with Fiscal Instances** 
* Count: 79733 
* Coverage: 97.29% 

**Filings with >=2 Fiscal Instances** 
* Count: 79522 
* Coverage: 97.03% 

**Filings with Matched Year over Year Quarterly Durations (QoQ)** 
* Count: 76367 
* Coverage: 93.18% 

**Filings with Matched Fiscal YTD over YTD Durations (YoY)** 
* Count: 75655 
* Coverage: 92.32% 

**Filings with Matched Fiscal Year End Over Document Period End Instances (FYED to DPED)**
* Count: 78605 
* Coverage: 95.91% 

**Filings with Year over Year Quarterly Percentage Features (QoQ)**  
* Count: 76367 
* Coverage: 93.18%

**Filings with Fiscal YTD over YTD Percentage Features (YoY)** 
* Count: 75655 
* Coverage: 92.32% 

**Filings with Matched Fiscal Year End Over Document Period End Percentage Features (FYED to DPED)** 
* Count: 78605 
* Coverage: 95.91% 

**Filings with a Combined GAAP Percentage Features File**  
* Count: 79733
* Coverage: 97.29% 



## Report Sections 
The remainder of this report shows detailed examples of the data extracted from a sample filing.  In addition, coverage explantions are provided for each type of filing data collected.    

1. GAAP Source Code Library Overview
2. Filing XBRL Overview
3. Fiscal Instant Data
4. Fiscal Duration Data
5. Filing Metadata and Text Blocks
6. Share Data
7. Ratio Data
8. GAAP Data Collection and Coverages
9. XBRL instance files
10. Raw GAAP Fact / Feature Files
11. GAAP Features Library
12. GAAP Feature Coverages
13. Filing Metadata View
14. Fiscal Durations View
15. Matched Fiscal Duration Views
16. Percentage Change Duration View
17. Fiscal Instances View
18. Matched Fiscal Instance Views
19. Percentage Change Instance Views
20. GAAP Percentage Features View
21. GAAP Full Data Repository

# GAAP Source Code Library Overview 
The GAAP source code library comprises functions and data repositories to collect and maintain all filing metadata and financials extracted from the XBRL facts in SEC 10-Q Filings.

* **XBRLInstance.py** - 193 lines
 * Get all latest taxonomies from the sec, updates the Py-XBRL parser
 * Finds any filings that do not have GAAP features extracted. 
 * Searches XBRL document collections. 
 * Identifies and extracts the XBRL instance document. 
 
* **GaapExtractor.py** - 102 lines (Recursive serialization to flatten XBRL fact metadata **possibly patentable**) 
 *  Recursively serializes all nested objects in each XBRL fact to collect all fact specific metadata provided by the filing's taxonomy.
 * Provides all filing facts, fact values, and fact metadata as a csv file.
 
* **GaapFeatures.py** - 918 lines (identification of QoQ, YoY, FYED_to_DPED and conversions to percentage changes **possibly patentable**)
 * Matches fiscal instance and duration periods within each filing. 
 * Creates all GAAP Feature views available for each filing.

* **GaapDataRepo.py** - 199 lines 
 * Creates the GAAP Full Data Repository dataframe, sparse feature matrix, and feature names index. 
 * GAAP_metadata_10Q_Full
 * GAAP_Pct_Chg_10Q_Full
 * GAAP_Pct_Chg_10Q_Full_Feature_Names

# Filing XBRL Overview
* Each compliant filing's XBRL document collection contains an XBRL instance document.
* XBRL instance documents contain all of the digital data disclosed by each company. 
* Individual data elements are stored in the XBRL instance document as XBRL Facts.  
* XBRL Facts are defined within taxonomies that contain all of the metadata relevant to each individual fact.
* The most common taxonomy for sec filings is the US-GAAP taxonomy. 
* However, a single filing typically contains many different taxonomies that define many different facts. 

### Example Filing - XBRL Facts and Associated Metadata
* The following list shows the XBRL Facts and metadata extracted for a single example filing.
* This filing has 41 columns of data related to the 648 XBRL facts disclosed. 
* The concept_name and value disclose the individual XBRL fact names and associated values. 

In [20]:
import pandas as pd
import Source.MonitorFilings.Parameters as params
from Source.GAAP.GaapFeatures import * 


file_name = '726865_0000726865-21-000388.csv'

date_cols = ['context_start_date','context_end_date','context_instant_date']
GAAP_csv = pd.read_csv(params.GAAP_dir + file_name, parse_dates=date_cols)

print('\n\nXBRL Facts and Associated Metadata Available\n\n')

GAAP_csv.info()



XBRL Facts and Associated Metadata Available


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648 entries, 0 to 647
Data columns (total 41 columns):
 #   Column                       Non-Null Count  Dtype         
---  ------                       --------------  -----         
 0   concept_xml_id               648 non-null    object        
 1   concept_schema_url           648 non-null    object        
 2   concept_name                 648 non-null    object        
 3   concept_substitution_group   648 non-null    object        
 4   concept_concept_type         0 non-null      float64       
 5   concept_abstract             648 non-null    bool          
 6   concept_nillable             648 non-null    bool          
 7   concept_period_type          648 non-null    object        
 8   concept_balance              529 non-null    object        
 9   concept_labels_0_label       648 non-null    object        
 10  concept_labels_0_language    648 non-null    object        
 

### XBRL Facts and Associated Metadata Sample
* Each XBRL fact contains the taxonomy, schema, and id that defines the fact.  
* It also contains detailed metadata about the fact that informs the user exactly what type of digital data is contained within each fact.

In [33]:
display_full_dataframe(GAAP_csv.tail(25))

concept_xml_id  \
623  us-gaap_FairValueAssetRecurringBasisStillHeldU...   
624  cik0000726865_FairValueAssetsAndLiabilitiesTra...   
625  us-gaap_FairValueMeasurementWithUnobservableIn...   
626  us-gaap_FairValueMeasurementWithUnobservableIn...   
627  us-gaap_FairValueMeasurementWithUnobservableIn...   
628  us-gaap_FairValueMeasurementWithUnobservableIn...   
629  us-gaap_FairValueMeasurementWithUnobservableIn...   
630  us-gaap_FairValueMeasurementWithUnobservableIn...   
631  us-gaap_FairValueMeasurementWithUnobservableIn...   
632  us-gaap_FairValueMeasurementWithUnobservableIn...   
633  us-gaap_FairValueMeasurementWithUnobservableIn...   
634  us-gaap_FairValueMeasurementWithUnobservableIn...   
635  us-gaap_FairValueMeasurementWithUnobservableIn...   
636  us-gaap_FairValueAssetsMeasuredOnNonrecurringB...   
637        us-gaap_SegmentReportingDisclosureTextBlock   
638  us-gaap_ReconciliationOfRevenueFromSegmentsToC...   
639                                   us-gaap_Revenues   
640                                   us-gaap_Revenues   
641                                   us-gaap_Revenues   
642                                   us-gaap_Revenues   
643  cik0000726865_ReconciliationOfIncomeLossFromOp...   
644                              us-gaap_NetIncomeLoss   
645                              us-gaap_NetIncomeLoss   
646                              us-gaap_NetIncomeLoss   
647                              us-gaap_NetIncomeLoss   

                                    concept_schema_url  \
623  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
624  https://www.sec.gov/Archives/edgar/data/726865...   
625  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
626  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
627  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
628  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
629  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
630  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
631  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
632  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
633  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
634  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
635  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
636  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
637  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
638  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
639  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
640  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
641  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
642  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
643  https://www.sec.gov/Archives/edgar/data/726865...   
644  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
645  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
646  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   
647  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...   

                                          concept_name  \
623  FairValueAssetRecurringBasisStillHeldUnrealize...   
624  FairValueAssetsAndLiabilitiesTransfersInAndOut...   
625  FairValueMeasurementWithUnobservableInputsReco...   
626  FairValueMeasurementWithUnobservableInputsReco...   
627  FairValueMeasurementWithUnobservableInputsReco...   
628  FairValueMeasurementWithUnobservableInputsReco...   
629  FairValueMeasurementWithUnobservableInputsReco...   
630  FairValueMeasurementWithUnobservableInputsReco...   
631  FairValueMeasurementWithUnobservableInputsReco...   
632  FairValueMeasurementWithUnobservableInputsReco...   
633  FairValueMeasurementWithUnobservableInputsReco...   
634  FairValueMeasurementWithUnobservableInputsReco...   
635  FairValueMeasurementWithUnobservableInputsReco...   
636  FairValueAssetsMeasuredOnNonrecurringBasisValu...   
637                SegmentReportingDisclosureTextBlock   
638  ReconciliationOfRevenueFromSegmentsToConsolida...   
639                                 

#### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**NOTE: All remaining data and GAAP feature views shown below are generated from the XBRL facts and metadata extracted from the XBRL Instance Document.**  
#### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Fiscal Instance Data

This data is a snapshot of the company's financial position at a specific point in time, usually at the end of a fiscal period. This can include information like assets, liabilities, and shareholders' equity at the fiscal year-end. This data allows investors to understand the company's current financial position, its assets and liabilities, and any changes since the end of the last fiscal year.

In SEC filings, Fiscal Instant Data represents a snapshot of each fact as of the context_instant_date. A balance sheet is a snapshot of a company's financial situation at a specific point in time, so the "context_instant_date" values represent when each of these snapshots was taken. 

Some of the instances disclosed in a filing may simply correspond to less extensive updates, while others correspond to full-blown financial reports with comprehensive disclosure requirements. The level of detail on particular fiscal instance dates is a reflection of the nature of the disclosures required at the end of key financial reporting periods. Adjustments may only contain only a few key XBRL facts, while instances for a fiscal period may contain an entire financial report.   

### Typical 10-Q Filing Instances

Most 10-Q filings disclose and compare at least two fiscal instances. 

* **Fiscal Year-End Date (FYED) to Document Period End Date (DPED):** Compares the balance sheet data (which provides a snapshot of the company's financial position at a specific point in time) at the end of the fiscal year with the balance sheet data at the end of the reporting period for the 10-Q filing.

In addition, many companies will also disclose instant data as of the last fiscal year end and sometimes the prior fiscal year end.  

### Fiscal Instant Data - Debits
* In SEC filings, Fiscal Instant Data represents a snapshot of each fact as of the context_instant_date. 
* The concept_balance also informs what type of balance sheet item we are looking at: (debit / credit / null). 
* In the example filing below, we can see:
 * All balance sheet debit snapshots and the date the snapshot was taken. 
 * All items appear to be in US dollars and captured at -6 decimals.
 * Inspecting the concept_schema_url also informs us that most of these debit items are defined in the US-GAAP taxonomy.
 * However, some items are derived from a custom taxonomy that is specific to the filer's CIK number and stored at the SEC. 
 * Some debits on the balance sheet are disclosed on up to 6 different instance dates.

In [39]:
df_cols = ['concept_name','context_instant_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.concept_balance == 'debit') & 
                       (GAAP_csv.concept_period_type == 'instant')
                      ].sort_values(['concept_name','context_instant_date'])

display_full_dataframe(df)

concept_name context_instant_date  \
55                   AccruedInvestmentIncomeReceivable           2020-12-31   
54                   AccruedInvestmentIncomeReceivable           2021-06-30   
67                                              Assets           2020-12-31   
66                                              Assets           2021-06-30   
27    AvailableForSaleDebtSecuritiesAmortizedCostBasis           2020-12-31   
26    AvailableForSaleDebtSecuritiesAmortizedCostBasis           2021-06-30   
31            AvailableForSaleSecuritiesDebtSecurities           2020-12-31   
30            AvailableForSaleSecuritiesDebtSecurities           2021-06-30   
253  CashCashEquivalentsRestrictedCashAndRestricted...           2019-12-31   
255  CashCashEquivalentsRestrictedCashAndRestricted...           2020-06-30   
49   CashCashEquivalentsRestrictedCashAndRestricted...           2020-12-31   
252  CashCashEquivalentsRestrictedCashAndRestricted...           2020-12-31   
48   CashCashEquivalentsRestrictedCashAndRestricted...           2021-06-30   
254  CashCashEquivalentsRestrictedCashAndRestricted...           2021-06-30   
331  CollateralPayableHeldForDerivativeInvestmentsF...           2020-12-31   
329  CollateralPayableHeldForDerivativeInvestmentsF...           2021-06-30   
51   DeferredPolicyAcquisitionCostsAndValueOfBusine...           2020-12-31   
50   DeferredPolicyAcquisitionCostsAndValueOfBusine...           2021-06-30   
424  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
396  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
431  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
403  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
419  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
391  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
43                                    DerivativeAssets           2020-12-31   
42                                    DerivativeAssets           2021-06-30   
387             DerivativeCollateralRightToReclaimCash           2020-12-31   
385             DerivativeCollateralRightToReclaimCash           2021-06-30   
422  DerivativeFairValueOfDerivativeAssetAmountNotO...           2020-12-31   
394  DerivativeFairValueOfDerivativeAssetAmountNotO...           2021-06-30   
429  DerivativeFairValueOfDerivativeAssetAmountOffs...           2020-12-31   
401  DerivativeFairValueOfDerivativeAssetAmountOffs...           2021-06-30   
417  DerivativeInstrumentsGrossAmountsOfRecognizedA...           2020-12-31   
389  DerivativeInstrumentsGrossAmountsOfRecognizedA...           2021-06-30   
440  DerivativeLiabilityCollateralRightToReclaimCas...           2020-12-31   
412  DerivativeLiabilityCollateralRightToReclaimCas...           2021-06-30   
435             DerivativeLiabilityFairValueGrossAsset           2020-12-31   
407             DerivativeLiabilityFairValueGrossAsset           2021-06-30   
436  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2020-12-31   
408  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2021-06-30   
441  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2020-12-31   
413  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2021-06-30   
35                                EquitySecuritiesFvNi           2020-12-31   
34                                EquitySecuritiesFvNi           2021-06-30   
381      ExposureAssociatedWithCollateralizationEvents           2020-12-31   
382      ExposureAssociatedWithCollateralizationEvents           2021-06-30   
584  FairValueNetDerivativeAssetLiabilityMeasuredOn...           2019-12-31   
572  FairValueNetDerivativeAssetLiabilityMeasuredOn...           2020-03-31   
577  FairValueNetDerivativeAssetLiabilityMeasuredOn...           2020-06-30   
589  FairValueNetDerivativeAssetLiabilityMeasuredOn...           2020-06-30   
578  FairValu

### Fiscal Instant Data - Credits
* In SEC filings, Fiscal Instant Data represents a snapshot of each fact as of the context_instant_date. 
* The concept_balance also informs what type of balance sheet item we are looking at: (debit / credit / null). 
* In the example filing below, we can see:
 * All balance sheet credit snapshots and the date the snapshot was taken. 
 * All items appear to be in US dollars and captured at -6 decimals.
 * Inspecting the concept_schema_url also informs us that most of these debit items are defined in the US-GAAP taxonomy.
 * However, some items are derived from a custom taxonomy that is specific to the filer's CIK number and stored at the SEC. 
 * Some credits on the balance sheet are disclosed up to 6 times.
 * While StockholdersEquity (last entry) is disclosed 6 different times, some of the instant dates and values are identical which indicates that the same data is likely displayed in multiple locations on this filing.   

In [40]:
df_cols = ['concept_name','context_instant_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.concept_balance == 'credit') & 
                       (GAAP_csv.concept_period_type == 'instant')
                      ].sort_values(['concept_name','context_instant_date'])

display_full_dataframe(df)

concept_name context_instant_date  \
99     AccumulatedOtherComprehensiveIncomeLossNetOfTax           2020-12-31   
98     AccumulatedOtherComprehensiveIncomeLossNetOfTax           2021-06-30   
330  CollateralPayableHeldForDerivativeInvestmentsC...           2020-12-31   
328  CollateralPayableHeldForDerivativeInvestmentsC...           2021-06-30   
95                         CommonStockValueOutstanding           2020-12-31   
94                         CommonStockValueOutstanding           2021-06-30   
73                                         DebtCurrent           2020-12-31   
72                                         DebtCurrent           2021-06-30   
281  DebtSecuritiesAvailableForSaleAllowanceForCred...           2020-03-31   
284  DebtSecuritiesAvailableForSaleAllowanceForCred...           2020-06-30   
287  DebtSecuritiesAvailableForSaleAllowanceForCred...           2020-06-30   
29   DebtSecuritiesAvailableForSaleAllowanceForCred...           2020-12-31   
277  DebtSecuritiesAvailableForSaleAllowanceForCred...           2020-12-31   
273  DebtSecuritiesAvailableForSaleAllowanceForCred...           2021-03-31   
28   DebtSecuritiesAvailableForSaleAllowanceForCred...           2021-06-30   
276  DebtSecuritiesAvailableForSaleAllowanceForCred...           2021-06-30   
280  DebtSecuritiesAvailableForSaleAllowanceForCred...           2021-06-30   
81   DepositsReceivedForSecuritiesLoanedAtCarryingV...           2020-12-31   
342  DepositsReceivedForSecuritiesLoanedAtCarryingV...           2020-12-31   
80   DepositsReceivedForSecuritiesLoanedAtCarryingV...           2021-06-30   
340  DepositsReceivedForSecuritiesLoanedAtCarryingV...           2021-06-30   
420             DerivativeAssetFairValueGrossLiability           2020-12-31   
392             DerivativeAssetFairValueGrossLiability           2021-06-30   
426  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
398  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
428  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
400  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
421  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2020-12-31   
393  DerivativeAssetSecuritiesPurchasedUnderAgreeme...           2021-06-30   
386         DerivativeCollateralObligationToReturnCash           2020-12-31   
425         DerivativeCollateralObligationToReturnCash           2020-12-31   
384         DerivativeCollateralObligationToReturnCash           2021-06-30   
397         DerivativeCollateralObligationToReturnCash           2021-06-30   
427   DerivativeCollateralObligationToReturnSecurities           2020-12-31   
399   DerivativeCollateralObligationToReturnSecurities           2021-06-30   
437  DerivativeFairValueOfDerivativeLiabilityAmount...           2020-12-31   
409  DerivativeFairValueOfDerivativeLiabilityAmount...           2021-06-30   
442  DerivativeFairValueOfDerivativeLiabilityAmount...           2020-12-31   
414  DerivativeFairValueOfDerivativeLiabilityAmount...           2021-06-30   
432  DerivativeInstrumentsGrossAmountOfRecognizedLi...           2020-12-31   
404  DerivativeInstrumentsGrossAmountOfRecognizedLi...           2021-06-30   
439  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2020-12-31   
411  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2021-06-30   
444  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2020-12-31   
416  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2021-06-30   
434  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2020-12-31   
406  DerivativeLiabilitySecuritiesSoldUnderAgreemen...           2021-06-30   
358  FairValueOfSecuritiesReceivedAsCollateralThatC...           2021-06-30   
313        FinancingReceivableAllowanceForCreditLosses           2019-12-31   
310        FinancingReceivableAllowanceForCreditLosses           2020-03-31   
312        Fi

# Fiscal Duration Data

Fiscal duration data represent durations over which income statement and cash flow data are accumulated. Typically the fiscal durations allow investors to see how the company is doing compared to a similar period in the past and determine if it's growing, stagnating, or declining.

**Typical 10-Q Filing Durations**

Most 10-Q filings disclose two durations for the current fiscal year and compare the data in these durations to the same time period from the previous year.   

* **Year-over-Year Quarterly Fiscal Durations (QoQ):** Compares a given quarter's data with the same quarter from the previous year. For example, you could compare Q2 2023 with Q2 2022.

* **YTD over YTD (Year-to-Date) Durations (YoY):** Compares the cumulative total for a given fiscal year up until a certain date with the cumulative total for the previous year up until the same date. For example, you could compare YTD as of Q2 2023 with YTD as of Q2 2022.

**NOTE**

In a perfect world, the dates or durations for two QoQ or YoY / YTD durations would match.  However, this is certainly NOT the case in practice.  For example, a current QoQ duration may cover 90 days and the prior year may cover 93 days etc.  Start and end dates may also be off by a few days. Furthermore, matching durations may not always disclose the exact same financial data elements.   

It takes some fairly sophisticated matching logic to ensure that the proper QoQ, YoY and YTD durations are matched. 

### Fiscal Duration Data - Debits
* In SEC filings, Fiscal Duration Data represents each fact's value between the context start and end dates.
* The concept_balance also informs what type of balance sheet item we are looking at: (debit / credit / null). 
* In the example filing below, we can see:
 * All balance sheet debits and values between the context start and end dates.
 * Units and taxonomies are the same as the fiscal instant data above. 
 * In the raw dataview, many of the fiscal duration elements are disclosed across multiple durations. 

In [42]:
df_cols = ['concept_name','context_start_date','context_end_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.concept_balance == 'debit') & 
                       (GAAP_csv.concept_period_type == 'duration')
                      ].sort_values(['concept_name','context_start_date', 'context_end_date'])

display_full_dataframe(df)

concept_name context_start_date  \
264  AffordableHousingTaxCreditsAndOtherTaxExpenseA...         2020-01-01   
155                          BenefitsLossesAndExpenses         2020-01-01   
153                          BenefitsLossesAndExpenses         2020-04-01   
154                          BenefitsLossesAndExpenses         2021-01-01   
152                          BenefitsLossesAndExpenses         2021-04-01   
251  CashCashEquivalentsRestrictedCashAndRestricted...         2020-01-01   
250  CashCashEquivalentsRestrictedCashAndRestricted...         2021-01-01   
288  DebtSecuritiesAvailableForSaleAccruedInterestW...         2020-01-01   
289  DebtSecuritiesAvailableForSaleAccruedInterestW...         2021-01-01   
285  DebtSecuritiesAvailableForSaleAllowanceForCred...         2020-01-01   
282  DebtSecuritiesAvailableForSaleAllowanceForCred...         2020-04-01   
278  DebtSecuritiesAvailableForSaleAllowanceForCred...         2021-01-01   
274  DebtSecuritiesAvailableForSaleAllowanceForCred...         2021-04-01   
286  DebtSecuritiesAvailableForSaleAllowanceForCred...         2020-01-01   
283  DebtSecuritiesAvailableForSaleAllowanceForCred...         2020-04-01   
279  DebtSecuritiesAvailableForSaleAllowanceForCred...         2021-01-01   
275  DebtSecuritiesAvailableForSaleAllowanceForCred...         2021-04-01   
189  DeferredAcquisitionCostsValueOfBusinessAcquire...         2020-01-01   
188  DeferredAcquisitionCostsValueOfBusinessAcquire...         2021-01-01   
238  DepositsOfFixedAccountValuesIncludingFixedPort...         2020-01-01   
237  DepositsOfFixedAccountValuesIncludingFixedPort...         2021-01-01   
608  FairValueMeasurementWithUnobservableInputsReco...         2020-01-01   
596  FairValueMeasurementWithUnobservableInputsReco...         2020-04-01   
602  FairValueMeasurementWithUnobservableInputsReco...         2021-01-01   
591  FairValueMeasurementWithUnobservableInputsReco...         2021-04-01   
613  FairValueMeasurementWithUnobservableInputsReco...         2020-01-01   
601  FairValueMeasurementWithUnobservableInputsReco...         2020-04-01   
607  FairValueMeasurementWithUnobservableInputsReco...         2021-01-01   
595  FairValueMeasurementWithUnobservableInputsReco...         2021-04-01   
633  FairValueMeasurementWithUnobservableInputsReco...         2020-01-01   
627  FairValueMeasurementWithUnobservableInputsReco...         2020-04-01   
630  FairValueMeasurementWithUnobservableInputsReco...         2021-01-01   
635  FairValueMeasurementWithUnobservableInputsReco...         2020-01-01   
629  FairValueMeasurementWithUnobservableInputsReco...         2020-04-01   
632  FairValueMeasurementWithUnobservableInputsReco...         2021-01-01   
626  FairValueMeasurementWithUnobservableInputsReco...         2021-04-01   
587  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2020-01-01   
575  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2020-04-01   
581  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2021-01-01   
569  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2021-04-01   
588  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2020-01-01   
576  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2020-04-01   
582  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2021-01-01   
570  FairValueNetDerivativeAssetLiabilityMeasuredOn...         2021-04-01   
321  FinancingReceivableChangeInPresentValueExpense...         2020-01-01   
320  FinancingReceivableChangeInPresentValueExpense...         2020-04-01   
317  FinancingReceivableChangeInPresentValueExpense...         2021-01-01   
316  FinancingReceivableChangeInPresentValueExpense...         2021-04-01   
163                            IncomeTaxExpenseBenefit         2020-01-01   
161                            IncomeTaxExpenseBenefit         2020-04-01   
162                            IncomeTaxExpenseBenefit         2021-01-01   
160                            IncomeT

### Fiscal Duration Data - Credits

In [43]:
df_cols = ['concept_name','context_start_date','context_end_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.concept_balance == 'credit') & 
                       (GAAP_csv.concept_period_type == 'duration')
                      ].sort_values(['concept_name','context_start_date', 'context_end_date'])

display_full_dataframe(df)

concept_name context_start_date  \
263  AffordableHousingTaxCreditsAndOtherTaxBenefits...         2021-01-01   
262  AffordableHousingTaxCreditsAndOtherTaxBenefits...         2021-04-01   
527  AmortizationAssociatedWithRealizedGainLossOnCe...         2020-01-01   
525  AmortizationAssociatedWithRealizedGainLossOnCe...         2020-04-01   
526  AmortizationAssociatedWithRealizedGainLossOnCe...         2021-01-01   
524  AmortizationAssociatedWithRealizedGainLossOnCe...         2021-04-01   
123  AmortizationOfDeferredGainOnBusinessSoldThroug...         2020-01-01   
187  AmortizationOfDeferredGainOnBusinessSoldThroug...         2020-01-01   
121  AmortizationOfDeferredGainOnBusinessSoldThroug...         2020-04-01   
122  AmortizationOfDeferredGainOnBusinessSoldThroug...         2021-01-01   
186  AmortizationOfDeferredGainOnBusinessSoldThroug...         2021-01-01   
120  AmortizationOfDeferredGainOnBusinessSoldThroug...         2021-04-01   
271  AvailableForSaleSecuritiesChangeInGrossUnreali...         2021-01-01   
375  CashFlowHedgeGainLossToBeReclassifiedWithinTwe...         2021-01-01   
376             CashFlowHedgeReclassifiedToEarningsNet         2020-01-01   
377             CashFlowHedgeReclassifiedToEarningsNet         2021-01-01   
244  CommonStockIssuedForBenefitPlansAndExcessTaxBe...         2020-01-01   
243  CommonStockIssuedForBenefitPlansAndExcessTaxBe...         2021-01-01   
175                        ComprehensiveIncomeNetOfTax         2020-01-01   
173                        ComprehensiveIncomeNetOfTax         2020-04-01   
174                        ComprehensiveIncomeNetOfTax         2021-01-01   
172                        ComprehensiveIncomeNetOfTax         2021-04-01   
119            DebtAndEquitySecuritiesRealizedGainLoss         2020-01-01   
183            DebtAndEquitySecuritiesRealizedGainLoss         2020-01-01   
554            DebtAndEquitySecuritiesRealizedGainLoss         2020-01-01   
117            DebtAndEquitySecuritiesRealizedGainLoss         2020-04-01   
552            DebtAndEquitySecuritiesRealizedGainLoss         2020-04-01   
118            DebtAndEquitySecuritiesRealizedGainLoss         2021-01-01   
182            DebtAndEquitySecuritiesRealizedGainLoss         2021-01-01   
553            DebtAndEquitySecuritiesRealizedGainLoss         2021-01-01   
116            DebtAndEquitySecuritiesRealizedGainLoss         2021-04-01   
551            DebtAndEquitySecuritiesRealizedGainLoss         2021-04-01   
519               EquitySecuritiesFvNiRealizedGainLoss         2020-01-01   
517               EquitySecuritiesFvNiRealizedGainLoss         2020-04-01   
518               EquitySecuritiesFvNiRealizedGainLoss         2021-01-01   
516               EquitySecuritiesFvNiRealizedGainLoss         2021-04-01   
623  FairValueAssetRecurringBasisStillHeldUnrealize...         2020-01-01   
621  FairValueAssetRecurringBasisStillHeldUnrealize...         2020-04-01   
622  FairValueAssetRecurringBasisStillHeldUnrealize...         2021-01-01   
620  FairValueAssetRecurringBasisStillHeldUnrealize...         2021-04-01   
612  FairValueInvestmentsEntitiesThatCalculateNetAs...         2020-01-01   
600  FairValueInvestmentsEntitiesThatCalculateNetAs...         2020-04-01   
606  FairValueInvestmentsEntitiesThatCalculateNetAs...         2021-01-01   
618  FairValueLiabilitiesMeasuredOnRecurringBasisCh...         2020-01-01   
616  FairValueLiabilitiesMeasuredOnRecurringBasisCh...         2020-04-01   
617  FairValueLiabilitiesMeasuredOnRecurringBasisCh...         2021-01-01   
615  FairValueLiabilitiesMeasuredOnRecurringBasisCh...         2021-04-01   
585  FairValueMeasurementWithUnobservableInputsReco...         2020-01-01   
573  FairValueMeasurementWithUnobservableInputsReco...         2020-04-01   
579  FairValueMeasurementWithUnobservableInputsReco...         2021-01-01   
567  FairValueMeasurementWithUnobservableInputsReco...         2021-04-01   
586  FairValueMeasurementWithUnobserva

# Filing Metadata and Text Blocks

**SEC filings also contain additional XBRL facts disclosing information such as:**

* **company details** - Name, Address, Country, Phone Number
* **filing specific metadata** - CurrentFiscalYearEndDate, DocumentFiscalPeriodFocus
* **accounting and report text blocks** - GainLossOnInvestmentsTextBlock, ScheduleOfRealizedGainLossTableTextBlock etc.
* **filing flags** - AmendmentFlag etc. (some filings contain many other flags)

In [46]:
df_cols = ['concept_name','context_start_date','context_end_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.concept_balance.isnull()) & (GAAP_csv.unit_unit.isnull())]

display_full_dataframe(df)

concept_name context_start_date  \
0                                        AmendmentFlag         2021-01-01   
1                             CurrentFiscalYearEndDate         2021-01-01   
2                            DocumentFiscalPeriodFocus         2021-01-01   
3                                EntityCentralIndexKey         2021-01-01   
4                         EntityCurrentReportingStatus         2021-01-01   
5                         EntityInteractiveDataCurrent         2021-01-01   
6                                         DocumentType         2021-01-01   
7                              DocumentQuarterlyReport         2021-01-01   
8                                DocumentPeriodEndDate         2021-01-01   
9                              DocumentFiscalYearFocus         2021-01-01   
10                            DocumentTransitionReport         2021-01-01   
11                                    EntityFileNumber         2021-01-01   
12                                EntityRegistrantName         2021-01-01   
13                 EntityIncorporationStateCountryCode         2021-01-01   
14                       EntityTaxIdentificationNumber         2021-01-01   
15                           EntityAddressAddressLine1         2021-01-01   
16                             EntityAddressCityOrTown         2021-01-01   
17                        EntityAddressStateOrProvince         2021-01-01   
18                          EntityAddressPostalZipCode         2021-01-01   
19                                        CityAreaCode         2021-01-01   
20                                    LocalPhoneNumber         2021-01-01   
21                                 EntityFilerCategory         2021-01-01   
22                                 EntitySmallBusiness         2021-01-01   
23                         EntityEmergingGrowthCompany         2021-01-01   
24                                  EntityShellCompany         2021-01-01   
256  OrganizationConsolidationBasisOfPresentationBu...         2021-01-01   
257                                 NatureOfOperations         2021-01-01   
259             BasisOfAccountingPolicyPolicyTextBlock         2021-01-01   
260  ScheduleOfNewAccountingPronouncementsAndChange...         2021-01-01   
261        ScheduleOfVariableInterestEntitiesTextBlock         2021-01-01   
265  InvestmentsInDebtAndMarketableEquitySecurities...         2021-01-01   
266  ScheduleOfAvailableForSaleSecuritiesReconcilia...         2021-01-01   
267  InvestmentsClassifiedByContractualMaturityDate...         2021-01-01   
268  AvailableForSaleSecuritiesContinuousUnrealized...         2021-01-01   
270  ScheduleOfAvailableForSaleSecuritesWhoseValueI...         2021-01-01   
272                AvailableForSaleSecuritiesTextBlock         2021-01-01   
290  CompositionOfCurrentAndPastDueMortgageLoansOnR...         2021-01-01   
299  ScheduleOfAverageCarryingValueOfImpairedMortga...         2021-01-01   
300          PastDueFinancingReceivablesTableTextBlock         2021-01-01   
303  AllowanceForCreditLossesOnFinancingReceivables...         2021-01-01   
326  ScheduleOfAvailableForSaleDebtSecuritiesCredit...         2021-01-01   
327  ScheduleOfSecuritiesFinancingTransactionsTextB...         2021-01-01   
346  ScheduleOfIncreaseDecreaseInPayablesForCollate...         2021-01-01   
355  TransferOfCertainFinancialAssetsAccountedForAs...         2021-01-01   
363  DerivativeInstrumentsAndHedgingActivitiesDiscl...         2021-01-01   
364  ScheduleOfDerivativeInstrumentsInStatementOfFi...         2021-01-01   
365           ScheduleOfDerivativeInstrumentsTextBlock         2021-01-01   
372  ScheduleOfFairValueHedgingInstrumentsStatement...         2021-01-01   
373  ChangeInOurUnrealizedGainOnDerivativeInstrumen...         2021-01-01   
374  ScheduleOfDerivativesInstrumentsStatementsOfFi...         2021-01-01   
378             DisclosureOfCreditDerivativesTextBlock         2021-01-01   
379          CollateralSupportAgreemen

# Share Data
* Some XBRL facts are disclosed in the form of shares.
* All the share data disclosed in this example filing is fiscal instant data meaning that it was disclosed as a snapshot on a particular instant date. 

In [52]:
df_cols = ['concept_name','context_instant_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.unit_unit == 'shares')].sort_values(['concept_name','context_instant_date'])

display_full_dataframe(df)

concept_name context_instant_date       value  \
88         CommonStockSharesAuthorized           2020-12-31  10000000.0   
89         CommonStockSharesAuthorized           2021-06-30  10000000.0   
90             CommonStockSharesIssued           2020-12-31  10000000.0   
91             CommonStockSharesIssued           2021-06-30  10000000.0   
92        CommonStockSharesOutstanding           2020-12-31  10000000.0   
93        CommonStockSharesOutstanding           2021-06-30  10000000.0   
25  EntityCommonStockSharesOutstanding           2021-08-09  10000000.0   

   concept_balance concept_period_type unit_unit  decimals  \
88             NaN             instant    shares       NaN   
89             NaN             instant    shares       NaN   
90             NaN             instant    shares       NaN   
91             NaN             instant    shares       NaN   
92             NaN             instant    shares       NaN   
93             NaN             instant    shares       NaN   
25             NaN             instant    shares       NaN   

                            concept_xml_id  \
88     us-gaap_CommonStockSharesAuthorized   
89     us-gaap_CommonStockSharesAuthorized   
90         us-gaap_CommonStockSharesIssued   
91         us-gaap_CommonStockSharesIssued   
92    us-gaap_CommonStockSharesOutstanding   
93    us-gaap_CommonStockSharesOutstanding   
25  dei_EntityCommonStockSharesOutstanding   

                                   concept_schema_url  
88  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
89  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
90  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
91  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
92  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
93  http://xbrl.fasb.org/us-gaap/2020/elts/us-gaap...  
25   https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd

# Ratio Data 
* Filers also disclose ratios.
* Ratios in this example filing are both fiscal instant and duration disclosures. 

In [53]:
df_cols = ['concept_name','context_start_date','context_end_date','context_instant_date','value','concept_balance','concept_period_type','unit_unit','decimals', 
          'concept_xml_id', 'concept_schema_url']

df = GAAP_csv[df_cols][(GAAP_csv.unit_unit == 'pure')]

display_full_dataframe(df)

concept_name context_start_date  \
324  AlternativeInvestmentsAsPercentageOfOverallInv...         2021-01-01   
325  AlternativeInvestmentsAsPercentageOfOverallInv...         2020-01-01   
344  CollateralObtainedPercentOfFairValueSecurities...                NaT   
345  CollateralObtainedPercentOfFairValueSecurities...                NaT   
446         EffectiveIncomeTaxRateContinuingOperations         2021-04-01   
447         EffectiveIncomeTaxRateContinuingOperations         2021-01-01   
448         EffectiveIncomeTaxRateContinuingOperations         2020-04-01   
449         EffectiveIncomeTaxRateContinuingOperations         2020-01-01   
450  EffectiveIncomeTaxRateReconciliationAtFederalS...         2020-01-01   
451  EffectiveIncomeTaxRateReconciliationAtFederalS...         2020-04-01   
452  EffectiveIncomeTaxRateReconciliationAtFederalS...         2021-01-01   
453  EffectiveIncomeTaxRateReconciliationAtFederalS...         2021-04-01   
454  EffectiveIncomeTaxRateReconciliationAtFederalS...         2020-04-01   
455  EffectiveIncomeTaxRateReconciliationOtherAdjus...         2020-04-01   
473  PercentOfTotalVariableAnnuitySeparateAccountVa...                NaT   
474  PercentOfTotalVariableAnnuitySeparateAccountVa...                NaT   
475             PercentOfPermanentLifeInsuranceInForce                NaT   
476             PercentOfPermanentLifeInsuranceInForce                NaT   
477               PercentOfPermanentLifeInsuranceSales         2021-04-01   
478               PercentOfPermanentLifeInsuranceSales         2021-01-01   
479               PercentOfPermanentLifeInsuranceSales         2020-04-01   
480               PercentOfPermanentLifeInsuranceSales         2020-01-01   

    context_end_date context_instant_date value concept_balance  \
324       2021-06-30                  NaT  0.02             NaN   
325       2020-12-31                  NaT  0.01             NaN   
344              NaT           2021-06-30  1.02             NaN   
345              NaT           2021-06-30  1.05             NaN   
446       2021-06-30                  NaT  0.15             NaN   
447       2021-06-30                  NaT  0.16             NaN   
448       2020-06-30                  NaT  0.36             NaN   
449       2020-06-30                  NaT  0.05             NaN   
450       2020-06-30                  NaT  0.21             NaN   
451       2020-06-30                  NaT  0.21             NaN   
452       2021-06-30                  NaT  0.21             NaN   
453       2021-06-30                  NaT  0.21             NaN   
454       2020-06-30                  NaT  0.21             NaN   
455       2020-06-30                  NaT  0.21             NaN   
473              NaT           2021-06-30  0.98             NaN   
474              NaT           2020-12-31  0.98             NaN   
475              NaT           2020-12-31  0.37             NaN   
476              NaT           2021-06-30  0.37             NaN   
477       2021-06-30                  NaT  0.15             NaN   
478       2021-06-30                  NaT  0.14             NaN   
479       2020-06-30                  NaT  0.37             NaN   
480       2020-06-30                  NaT  0.33             NaN   

    concept_period_type unit_unit  decimals  \
324            duration      pure       2.0   
325            duration      pure       2.0   
344             instant      pure       2.0   
345             instant      pure       2.0   
446            duration      pure       2.0   
447            duration      pure       2.0   
448            duration      pure       2.0   
449            duration      pure       2.0   
450            duration      pure       NaN   
451            duration      pure       NaN   
452            duration      pure       NaN   
453            duration      pure       NaN   
454            duration      pure       NaN   
455            duration      pure       2.0   
473             instant

# GAAP Data Collection and Coverages
* The current filing and GAAP data collection includes over 81,000 filings from 2019 - Present.
* Filings are captured in near real time using the SEC RSS feed and Edgar data repositories. 

In [67]:
import os, os.path
import Source.MonitorFilings.Parameters as params

def get_percent(ct, tot):
    pct = (ct / tot) * 100
    return round(pct, 2)

total_filings = len(os.listdir(params.sec_raw_filings_dir))
print('Total 10Q Filings:' , total_filings)

Total 10Q Filings: 81953


### Get all the GAAP File Paths for the Example Filing Above

In [61]:
from Source.GAAP.GaapFeatures import * 

# Get the file paths for all of the GAAP feature files we just created
GAAP_paths = get_GAAP_file_paths(file_name)

GAAP_paths.keys()

dict_keys(['path_10Q_XBRL_Instance', 'path_10Q_GAAP_Raw', 'path_10Q_GAAP_Features'])

# XBRL instance files 
The XBRL instance document contains all of the namespaces, taxonomies, filing data, and metadata provided by each company for a given filing. 

In [70]:
xbrl_instances = len(os.listdir(params.XBRL_instance_dir))
print('Total 10Q Xbrl Instances:' , xbrl_instances)
print('Xbrl Instance Coverage:', get_percent(xbrl_instances, total_filings))

Total 10Q Xbrl Instances: 81885
Xbrl Instance Coverage: 99.92


**A sample of the example filing's extracted XBRL instance document:**

In [71]:
with open(GAAP_paths['path_10Q_XBRL_Instance'], 'r') as file:
    xbrl_instance = file.read()
    
print(xbrl_instance[:10000])

<?xml version="1.0" encoding="utf-8"?>
<xbrl
  xmlns="http://www.xbrl.org/2003/instance"
  xmlns:cik0000726865="http://lfg.com/20210630"
  xmlns:dei="http://xbrl.sec.gov/dei/2020-01-31"
  xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
  xmlns:link="http://www.xbrl.org/2003/linkbase"
  xmlns:srt="http://fasb.org/srt/2020-01-31"
  xmlns:stpr="http://xbrl.sec.gov/stpr/2018-01-31"
  xmlns:us-gaap="http://fasb.org/us-gaap/2020-01-31"
  xmlns:xbrldi="http://xbrl.org/2006/xbrldi"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <link:schemaRef xlink:href="c865-20210630.xsd" xlink:type="simple"/>
    <context id="Duration_1_1_2021_To_6_30_2021_srt_OwnershipAxis_cik0000726865_LincolnLifeAnnuityCompanyOfNewYorkMember">
        <entity>
            <identifier scheme="http://www.sec.gov/CIK">0000726865</identifier>
            <segment>
                <xbrldi:explicitMember dimension="srt:OwnershipAxis">cik0000726865:LincolnLifeAnnuityCo

# Raw GAAP Fact / Feature Files
* One .csv file per filing is created containing all financial and metadata extracted from the XBRL instance document.  
* Each row contains the data feature name, value, debit / credit, ratio, decimal place precision, all available labels and descriptions, denominations (USD, shares etc), taxonomy and namespace urls, and context instant, start, and end dates.  
* A row in this file could be filing metadata like a CIK number, company name, or ticker.  
* It could also be a fiscal duration or instant data element from the balance sheet.  
* You could literally recreate all digital tables in the filing and / or the company balance sheet using this file.

In [72]:
gaap_fact_files = len(os.listdir(params.GAAP_dir))
print('Total 10Q GAAP Fact Files:' , gaap_fact_files)
print('GAAP Fact File Coverage:', get_percent(gaap_fact_files, total_filings))

Total 10Q GAAP Fact Files: 79816
GAAP Fact File Coverage: 97.39


### GAAP Facts Sample- Example Filing

In [76]:
import pandas as pd

date_cols = ['context_start_date','context_end_date','context_instant_date']
GAAP_raw = pd.read_csv(GAAP_paths['path_10Q_GAAP_Raw'], parse_dates=date_cols)

with pd.option_context('display.max_columns', None):
    display(GAAP_raw.head(5))

concept_xml_id  \
0                 dei_AmendmentFlag   
1      dei_CurrentFiscalYearEndDate   
2     dei_DocumentFiscalPeriodFocus   
3         dei_EntityCentralIndexKey   
4  dei_EntityCurrentReportingStatus   

                                 concept_schema_url  \
0  https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd   
1  https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd   
2  https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd   
3  https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd   
4  https://xbrl.sec.gov/dei/2020/dei-2020-01-31.xsd   

                   concept_name concept_substitution_group  \
0                 AmendmentFlag                       item   
1      CurrentFiscalYearEndDate                       item   
2     DocumentFiscalPeriodFocus                       item   
3         EntityCentralIndexKey                       item   
4  EntityCurrentReportingStatus                       item   

   concept_concept_type  concept_abstract  concept_nillable  \
0                   NaN             False              True   
1                   NaN             False              True   
2                   NaN             False              True   
3                   NaN             False              True   
4                   NaN             False              True   

  concept_period_type concept_balance                concept_labels_0_label  \
0            duration             NaN                 dei_AmendmentFlag_lbl   
1            duration             NaN      dei_CurrentFiscalYearEndDate_lbl   
2            duration             NaN     dei_DocumentFiscalPeriodFocus_lbl   
3            duration             NaN         dei_EntityCentralIndexKey_lbl   
4            duration             NaN  dei_EntityCurrentReportingStatus_lbl   

  concept_labels_0_language            concept_labels_0_text  \
0                     en-US                   Amendment Flag   
1                     en-US     Current Fiscal Year End Date   
2                     en-US     Document Fiscal Period Focus   
3                     en-US         Entity Central Index Key   
4                     en-US  Entity Current Reporting Status   

           concept_labels_0_label_type                 concept_type  \
0  http://www.xbrl.org/2003/role/label        xbrli:booleanItemType   
1  http://www.xbrl.org/2003/role/label      xbrli:gMonthDayItemType   
2  http://www.xbrl.org/2003/role/label     dei:fiscalPeriodItemType   
3  http://www.xbrl.org/2003/role/label  dei:centralIndexKeyItemType   
4  http://www.xbrl.org/2003/role/label            dei:yesNoItemType   

                   context_xml_id  context_entity context_start_date  \
0  Duration_1_1_2021_To_6_30_2021          726865         2021-01-01   
1  Duration_1_1_2021_To_6_30_2021          726865         2021-01-01   
2  Duration_1_1_2021_To_6_30_2021          726865         2021-01-01   
3  Duration_1_1_2021_To_6_30_2021          726865         2021-01-01   
4  Duration_1_1_2021_To_6_30_2021          726865         2021-01-01   

  context_end_date       value  \
0       2021-06-30       false   
1       2021-06-30     --12-31   
2       2021-06-30          Q2   
3       2021-06-30  0000726865   
4       2021-06-30         Yes   

                                              xml_id  footnote  \
0  ct-nonNumeric-88688092-ee75-41c1-a4b5-bc0333c6...       NaN   
1  ct-nonNumeric-5eec7d87-668b-4a48-b1d0-ea69d076...       NaN   
2  ct-nonNumeric-c8f04bb5-415d-4c56-8797-aca2d00e...       NaN   
3  ct-nonNumeric-7a1b7e9d-60f8-44c0-90f6-8fc747ec...       NaN   
4  ct-nonNumeric-769e388f-04f5-47a5-9827-9a27801f...       NaN   

  context_instant_date unit_unit_id unit_unit  decimals  \
0                  NaT          NaN       NaN       NaN   
1                  NaT          NaN       NaN       NaN   
2                  NaT          NaN       NaN       NaN   
3                  NaT          NaN       NaN       NaN   
4                  NaT          NaN       NaN       NaN   

  concept_labels_1_label c

# Gaap Features Library
The GaapFeatures.py library extracts all XBRL facts for each filing.  Facts are then organized into multiple GAAP feature views stored at the filing level and in the full 10Q_GAAP_Features data repo. 

### 10Q_GAAP_Features Data Repo
* Dictionary file containing all current views of the GAAP and filing data.  
* The coverage number below indicates that at least one view exists per filing.
* Some filings are non-compliant and do not contain a XBRL instance document. 
* Other filings may disclose only metadata or very limited financial data. 
* As a result, some filing's 10Q_GAAP_Features file may not contain all possible views. 

In [77]:
gaap_feature_files = len(os.listdir(params.GAAP_features_dir))
print('Total 10Q GAAP Feature Files:' , gaap_feature_files)
print('GAAP Fact File Coverage:', get_percent(gaap_feature_files, total_filings))

Total 10Q GAAP Feature Files: 79733
GAAP Fact File Coverage: 97.29


### GAAP Feature Views Currently Processed
The following list contains all of the GAAP feature views that are currently supported.  The remaining sections show coverages, definitions, and examples for each view type.

In [80]:
from Source.MonitorFilings.PersistedParameters import load_from_pickle

GAAP_features = load_from_pickle(GAAP_paths['path_10Q_GAAP_Features'])

print('\nCurrent GAAP Feature Views Available:\n')

for k in GAAP_features.keys():
    print(k)


Current GAAP Feature Views Available:

gaap_metadata
gaap_FD
gaap_FI
QoQ
YoY
FYED_to_DPED
QoQ_pct
YoY_pct
FYED_to_DPED_pct
gaap_pct_features


### GAAP Feature Library Counts
Here I inspect the GAAP feature file for every single filing and count the GAAP feature view coverages.

In [99]:
# Create and init all count keys to 0 
gaap_feature_counts = {}
gaap_feature_counts['gaap_feature_files'] = 0
gaap_feature_counts['gaap_metadata'] = 0
gaap_feature_counts['gaap_FD'] = 0
gaap_feature_counts['gaap_FD_GE_2'] = 0
gaap_feature_counts['gaap_FI'] = 0
gaap_feature_counts['gaap_FI_GE_2'] = 0 
gaap_feature_counts['QoQ'] = 0 
gaap_feature_counts['YoY'] = 0
gaap_feature_counts['FYED_to_DPED'] = 0
gaap_feature_counts['QoQ_pct'] = 0
gaap_feature_counts['YoY_pct'] = 0
gaap_feature_counts['FYED_to_DPED_pct'] = 0 
gaap_feature_counts['gaap_pct_features'] = 0 

# Count coverages for all GAAP_Feature files
for f_name in os.listdir(params.GAAP_features_dir):
    
    gf = load_from_pickle(params.GAAP_features_dir + f_name)
    
    # Count each file processed
    gaap_feature_counts['gaap_feature_files'] += 1 
    
    # Count metadata files
    if gf.get('gaap_metadata') is not None:
        gaap_feature_counts['gaap_metadata'] += 1 
        
    # Count fiscal duration data records
    gaap_FD = gf.get('gaap_FD')
    
    if gaap_FD is not None:
        gaap_feature_counts['gaap_FD'] += 1 
        
        if len(gaap_FD) >= 2:
            gaap_feature_counts['gaap_FD_GE_2'] += 1
            
            # No need to count FD matches, unless there are at least 2 FD records
            if gf.get('QoQ') is not None:
                gaap_feature_counts['QoQ'] += 1 
                
            if gf.get('YoY') is not None:
                gaap_feature_counts['YoY'] += 1 
                
            if gf.get('QoQ_pct') is not None:
                gaap_feature_counts['QoQ_pct'] += 1 
                
            if gf.get('YoY_pct') is not None:
                gaap_feature_counts['YoY_pct'] += 1 
            
    # Count fiscal instancce data records
    gaap_FI = gf.get('gaap_FI')
    
    if gaap_FI is not None:
        gaap_feature_counts['gaap_FI'] += 1 
        
        if len(gaap_FI) >= 2:
            gaap_feature_counts['gaap_FI_GE_2'] += 1
            
            # No need to count FI matches, unless there are at least 2 FI records
            if gf.get('FYED_to_DPED') is not None:
                gaap_feature_counts['FYED_to_DPED'] += 1
            
            if gf.get('FYED_to_DPED_pct') is not None:
                gaap_feature_counts['FYED_to_DPED_pct'] += 1
                
    if gf.get('gaap_pct_features') is not None:
        gaap_feature_counts['gaap_pct_features'] += 1

gaap_feature_counts

{'gaap_feature_files': 79733,
 'gaap_metadata': 79733,
 'gaap_FD': 79733,
 'gaap_FD_GE_2': 79341,
 'gaap_FI': 79733,
 'gaap_FI_GE_2': 79522,
 'QoQ': 76367,
 'YoY': 75655,
 'FYED_to_DPED': 78605,
 'QoQ_pct': 76367,
 'YoY_pct': 75655,
 'FYED_to_DPED_pct': 78605,
 'gaap_pct_features': 79733}

# GAAP Feature Coverages
Based on the counts above, we have:

**>= 97% coverage for:**
 * GAAP feature files
 * Filing metadata
 * Fiscal Durations 
 * Fiscal Instances
 
**>= 95% Coverage for:**
 * Fiscal year end instance data
 * Document period end instance data 
 * FYED_to_DPED instance matches - Compares the balance sheet data (which provides a snapshot of the company's financial position at a specific point in time) at the end of the fiscal year with the balance sheet data at the end of the reporting period for the 10-Q filing.
 * FYED_to_DPED_pct - Percentage data for all instance data elements that occur in both the fiscal year end and document period ending instance data. 
 
**>= 92% Coverage for:** 
 * Year over year and YoY percentage duration data
 * YTD over YTD and YTD percentage duration data

In [104]:
for k, v in gaap_feature_counts.items():
    print(k, '\nCount:',v,'Coverage:', get_percent(v, total_filings),'\n')

gaap_feature_files 
Count: 79733 Coverage: 97.29 

gaap_metadata 
Count: 79733 Coverage: 97.29 

gaap_FD 
Count: 79733 Coverage: 97.29 

gaap_FD_GE_2 
Count: 79341 Coverage: 96.81 

gaap_FI 
Count: 79733 Coverage: 97.29 

gaap_FI_GE_2 
Count: 79522 Coverage: 97.03 

QoQ 
Count: 76367 Coverage: 93.18 

YoY 
Count: 75655 Coverage: 92.32 

FYED_to_DPED 
Count: 78605 Coverage: 95.91 

QoQ_pct 
Count: 76367 Coverage: 93.18 

YoY_pct 
Count: 75655 Coverage: 92.32 

FYED_to_DPED_pct 
Count: 78605 Coverage: 95.91 

gaap_pct_features 
Count: 79733 Coverage: 97.29 



# Filing Metadata View
In addition to GAAP data, filers disclose a substancial amount of other filing metadata as well. 

**A few examples include:** 
 * Company Name
 * Ticker
 * CurrentFiscalYearEndDate
 * DocumentPeriodEndDate
 * Flags (AmendmentFlag, EntitySmallBusiness, EntityEmergingGrowthCompany) etc.
 * Periods (LesseeFinanceLeaseRenewalTerm1, FinanceLeaseWeightedAverageRemainingLeaseTerm1)
 * Categories (i.e. EntityFilerCategory)

### Metadata View - Example Filing
**Filing metadata is currently captured for all fillings with 97.29% coverage.**

In [81]:
GAAP_features['gaap_metadata']

{'AmendmentFlag': 'false',
 'CurrentFiscalYearEndDate': '--12-31',
 'DocumentFiscalPeriodFocus': 'Q2',
 'EntityCentralIndexKey': '0000726865',
 'EntityCurrentReportingStatus': 'Yes',
 'EntityInteractiveDataCurrent': 'Yes',
 'DocumentType': '10-Q',
 'DocumentQuarterlyReport': 'true',
 'DocumentPeriodEndDate': '2021-06-30',
 'DocumentFiscalYearFocus': '2021',
 'DocumentTransitionReport': 'false',
 'EntityFileNumber': '000-55871',
 'EntityRegistrantName': 'THE LINCOLN NATIONAL LIFE INSURANCE COMPANY',
 'EntityIncorporationStateCountryCode': 'IN',
 'EntityTaxIdentificationNumber': '35-0472300',
 'EntityAddressAddressLine1': '1300 South Clinton Street',
 'EntityAddressCityOrTown': 'Fort Wayne',
 'EntityAddressStateOrProvince': 'IN',
 'EntityAddressPostalZipCode': '46802',
 'CityAreaCode': '260',
 'LocalPhoneNumber': '455-2000',
 'EntityFilerCategory': 'Non-accelerated Filer',
 'EntitySmallBusiness': 'false',
 'EntityEmergingGrowthCompany': 'false',
 'EntityShellCompany': 'false'}

# Fiscal Durations View 
* The fiscal durations view is a pandas dataframe containing all fiscal durations disclosed within a filing.
* Each row represents a separate fiscal duration and includes the durations context start and end date. 
* Dataframe columns contain all fiscal duration features disclosed in a filing.
* Fiscal duration features that are missing from a particular duration will contain a value of NaN. 
* Rows are sorted by the context start and end dates.

**Scrolling to the far right the fiscal duration view also shows:**
 * **duration_days** - The number days in the duration 
 * **duration_YTD_days_dist** - The absolute distance in days from the filings YTD days of (90, 180, 270, 360) based on quarter.
 * **duration_fiscal_YTD_days_dist** - The absolute distance in days from the filings fiscal YTD days based on the last fiscal year end date and the document period end date.
 * **duration_90_days_dist** - The absolute distance in days from 90 days. 

### Fiscal Durations View - Example Filing
**Filings reporting at least 1 fiscal duration:**
 * Count: 79733 
 * Coverage: 97.29%
 
**Filings reporting at >= 2 fiscal durations:** 
 * Count: 79341 
 * Coverage: 96.81%

In [106]:
GAAP_features['gaap_FD']

concept_name context_start_date context_end_date  \
0                    2020-01-01       2020-06-30   
1                    2020-01-01       2020-12-31   
2                    2020-04-01       2020-06-30   
3                    2021-01-01       2021-06-30   
4                    2021-04-01       2021-06-30   

concept_name  AffordableHousingTaxCreditsAndOtherTaxBenefitsAmount  \
0                                                           NaN      
1                                                           NaN      
2                                                           NaN      
3                                                     2000000.0      
4                                                     1000000.0      

concept_name  AffordableHousingTaxCreditsAndOtherTaxExpenseAmount  \
0                                                    -1000000.0     
1                                                           NaN     
2                                                           NaN     
3                                                           NaN     
4                                                           NaN     

concept_name  AlternativeInvestmentsAsPercentageOfOverallInvestedAssets  \
0                                                           NaN           
1                                                          0.01           
2                                                           NaN           
3                                                          0.02           
4                                                           NaN           

concept_name  AmortizationAssociatedWithRealizedGainLossOnCertainInvestments  \
0                                                    43000000.0                
1                                                           NaN                
2                                                    18000000.0                
3                                                   -10000000.0                
4                                                    -5000000.0                

concept_name  AmortizationOfDeferredGainOnBusinessSoldThroughReinsurance  \
0                                                    18000000.0            
1                                                           NaN            
2                                                     9000000.0            
3                                                    14000000.0            
4                                                     7000000.0            

concept_name  AvailableForSaleSecuritiesChangeInGrossUnrealizedHoldingGainLoss  \
0                                                           NaN                  
1                                                           NaN                  
2                                                           NaN                  
3                                                   120000000.0                  
4                                                           NaN                  

concept_name  BenefitsLossesAndExpenses  \
0                          7.397000e+09   
1                                   NaN   
2                          3.757000e+09   
3                          8.018000e+09   
4                          3.891000e+09   

concept_name  CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect  \
0                                                  1.340000e+09                                                                
1                                                           NaN                                                                
2                                                           NaN                                                                
3                                                  4.520000e+08                                                                
4                                                           NaN       

### Durations Disclosed in the Example Filing
When considering the filing metadata, context_start_date, context_end_date, and duration_days we see the following fiscal durations disclosed in the example filing:

**Last Fiscal Year Duration**
* CurrentFiscalYearEndDate: --12-31
* DocumentPeriodEndDate: 2021-06-30
* Last fiscal year end: 2020-12-31 
* Last Fiscal Year Duration: 2020-01-01 to 2020-12-31 	

**Year-over-Year (QoQ) Quarterly Fiscal Durations**
 * The most recent quarterly duration disclosed is: 2021-04-01 to 2021-06-30 (90 days)	
 * The prior year quarterly duration disclosed is: 2020-04-01 to 2020-06-30 (90 days)
 * The dates and / or days do not always match in other filings.  
 
**YTD-over-YTD (YoY) Year to Date Fiscal Durations**
 * The DocumentFiscalPeriodFocus is Q2 
 * The fiscal YTD days is 180
 * The most recent YTD duration disclosed is: 2021-01-01 to 2021-06-30 (180 days)
 * The prior year YTD duration disclosed is: 2020-01-01	to 2020-06-30 (181 days)		
 * The dates and / or days do not always match in other filings.  


In [110]:
metadata = GAAP_features['gaap_metadata'] 
print('CurrentFiscalYearEndDate:', metadata['CurrentFiscalYearEndDate'])
print('DocumentPeriodEndDate:', metadata['DocumentPeriodEndDate'])
print('DocumentFiscalPeriodFocus:', metadata['DocumentFiscalPeriodFocus'])

GAAP_features['gaap_FD'][['context_start_date','context_end_date','duration_days']]

CurrentFiscalYearEndDate: --12-31
DocumentPeriodEndDate: 2021-06-30
DocumentFiscalPeriodFocus: Q2


concept_name context_start_date context_end_date duration_days
0                    2020-01-01       2020-06-30      181 days
1                    2020-01-01       2020-12-31      365 days
2                    2020-04-01       2020-06-30       90 days
3                    2021-01-01       2021-06-30      180 days
4                    2021-04-01       2021-06-30       90 days

# Matched Fiscal Duration Views

**The GaapFeatures library currently matches two different types of fiscal durations for all filings:**
* QoQ - The QoQ view currently captures the most recent quarterly duration disclosed on a filing and the same period for the prior year when they exist. 
* YoY - The YoY view currently captures the most recent YTD duration disclosed on a filing and the same period for the prior year when they exist. 

**Year over Year Quarterly Durations QoQ** 
* Count: 76367 
* Coverage: 93.18%

**Fiscal YTD over YTD Durations YoY**
* Count: 75655 
* Coverage: 92.32%

**Matching these durations is complex for a number of reasons including:**
* Start and end dates disclosed do not always match the expected quarterly or YTD ranges when considering the fiscal year end and document period end. In many cases, the dates will be within 7 days of the expected date.
* Quarterly durations are not always 90 days.
* Year over year quarterly durations do not always have the same number of days. For example, the most recent quarter may cover 90 days and the prior year's quarter may cover 94 days. 
* Fiscal YTD durations change based on the current fiscal quarter.
* Fiscal YTD durations do not always cover exactly (90, 180, 270, or 360) days.
* Matched fiscal YTD durations do not necessarily cover the same exact number of days. 

In [127]:
GAAP_features['QoQ']

concept_name context_start_date context_end_date  \
2                    2020-04-01       2020-06-30   
4                    2021-04-01       2021-06-30   

concept_name  AmortizationAssociatedWithRealizedGainLossOnCertainInvestments  \
2                                                    18000000.0                
4                                                    -5000000.0                

concept_name  AmortizationOfDeferredGainOnBusinessSoldThroughReinsurance  \
2                                                     9000000.0            
4                                                     7000000.0            

concept_name  BenefitsLossesAndExpenses  ComprehensiveIncomeNetOfTax  \
2                          3.757000e+09                 3.897000e+09   
4                          3.891000e+09                 2.183000e+09   

concept_name  DebtAndEquitySecuritiesRealizedGainLoss  \
2                                        -433000000.0   
4                                        -172000000.0   

concept_name  DebtSecuritiesAvailableForSaleAllowanceForCreditLossWriteoff  \
2                                                    15000000.0              
4                                                     6000000.0              

concept_name  EffectiveIncomeTaxRateContinuingOperations  \
2                                                   0.36   
4                                                   0.15   

concept_name  EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate  \
2                                                          0.21                     
4                                                          0.21                     

concept_name  ...  PercentOfPermanentLifeInsuranceSales  \
2             ...                                  0.37   
4             ...                                  0.15   

concept_name  PolicyholderBenefitsAndClaimsIncurredNet  PremiumsEarnedNet  \
2                                         1.870000e+09       1.285000e+09   
4                                         1.848000e+09       1.328000e+09   

concept_name  ProvisionForLoanLossesExpensedAllowanceRecorded  \
2                                                 111000000.0   
4                                                 -14000000.0   

concept_name  RealizedGainLossOnMarkToMarketOnCertainInstruments  \
2                                                  -235000000.0    
4                                                  -131000000.0    

concept_name      Revenues  StrategicDigitizationExpense  \
2             3.531000e+09                    14000000.0   
4             4.435000e+09                    21000000.0   

concept_name  TotalRealizedGainLossRelatedToCertainInvestments  \
2                                                 -138000000.0   
4                                                   19000000.0   

concept_name  VariableAnnuityNetDerivativesResultsAssociatedAmortizationIncomeExpense  \
2                                                     8000000.0                         
4                                                     8000000.0                         

concept_name  VariableAnnuityNetDerivativesResultsGrossGainLoss  
2                                                   -51000000.0  
4                                                   -62000000.0  

[2 rows x 47 columns]

In [133]:
print('Financial Features Captured for the QoQ view:',len(GAAP_features['QoQ'].columns))

Financial Features Captured for the QoQ view: 47


In [134]:
GAAP_features['YoY']

concept_name context_start_date context_end_date  \
0                    2020-01-01       2020-06-30   
3                    2021-01-01       2021-06-30   

concept_name  AmortizationAssociatedWithRealizedGainLossOnCertainInvestments  \
0                                                    43000000.0                
3                                                   -10000000.0                

concept_name  AmortizationOfDeferredGainOnBusinessSoldThroughReinsurance  \
0                                                    18000000.0            
3                                                    14000000.0            

concept_name  BenefitsLossesAndExpenses  \
0                          7.397000e+09   
3                          8.018000e+09   

concept_name  CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect  \
0                                                  1.340000e+09                                                                
3                                                  4.520000e+08                                                                

concept_name  CashFlowHedgeReclassifiedToEarningsNet  \
0                                                0.0   
3                                                0.0   

concept_name  CommonStockIssuedForBenefitPlansAndExcessTaxBenefits  \
0                                                     7000000.0      
3                                                    11000000.0      

concept_name  ComprehensiveIncomeNetOfTax  \
0                            2.337000e+09   
3                           -5.340000e+08   

concept_name  DebtAndEquitySecuritiesRealizedGainLoss  ...  \
0                                        -435000000.0  ...   
3                                          39000000.0  ...   

concept_name  RepaymentAndMaturitiesOfMortgageLoansOnRealEstate  \
0                                                   596000000.0   
3                                                   846000000.0   

concept_name  RepaymentsOfLongTermDebt      Revenues  \
0                           30000000.0  7.772000e+09   
3                           60000000.0  9.124000e+09   

concept_name  StrategicDigitizationExpense  \
0                               26000000.0   
3                               35000000.0   

concept_name  SupplementalInformationForPropertyCasualtyInsuranceUnderwritersCurrentYearClaimsAndClaimsAdjustmentExpense  \
0                                                  1.742000e+09                                                            
3                                                  1.932000e+09                                                            

concept_name  TotalRealizedGainLossRelatedToCertainInvestments  \
0                                                 -222000000.0   
3                                                   51000000.0   

concept_name  TransfersToAndFromSeparateAccountsNet  \
0                                      -216000000.0   
3                                       229000000.0   

concept_name  VariableAnnuityNetDerivativesResultsAssociatedAmortizationIncomeExpense  \
0                                                    17000000.0                         
3                                                    16000000.0                         

concept_name  VariableAnnuityNetDerivativesResultsGrossGainLoss  \
0                                                  -110000000.0   
3                                                  -113000000.0   

concept_name  WithdrawalsOfFixedAccountValuesIncludingFixedPortionOfVariable  
0                                                  3.291000e+09               
3                                                  3.283000e+09               

[2 rows x 97 columns]

In [135]:
print('Financial Features Captured for the YTD view:',len(GAAP_features['YoY'].columns))

Financial Features Captured for the YTD view: 97


# Percentage Change Duration Views 
**Percentage changes are calculated for all financial features disclosed in both views.**

**Year over Year Quarterly Percentages QoQ_pct** 
* Count: 76367 
* Coverage: 93.18%  

**Fiscal YTD over YTD Percentages YoY_pct**
* Count: 75655 
* Coverage: 92.32% 

In [136]:
GAAP_features['QoQ_pct']

period_start_QoQ period_end_QoQ  \
0       2020-04-01     2021-06-30   

   AmortizationAssociatedWithRealizedGainLossOnCertainInvestments_QoQ  \
0                                          -1.277778                    

   AmortizationOfDeferredGainOnBusinessSoldThroughReinsurance_QoQ  \
0                                          -0.222222                

   BenefitsLossesAndExpenses_QoQ  ComprehensiveIncomeNetOfTax_QoQ  \
0                       0.035667                        -0.439826   

   DebtAndEquitySecuritiesRealizedGainLoss_QoQ  \
0                                    -0.602771   

   DebtSecuritiesAvailableForSaleAllowanceForCreditLossWriteoff_QoQ  \
0                                               -0.6                  

   EffectiveIncomeTaxRateContinuingOperations_QoQ  \
0                                       -0.583333   

   EffectiveIncomeTaxRateReconciliationAtFederalStatutoryIncomeTaxRate_QoQ  \
0                                                0.0                         

   ...  PercentOfPermanentLifeInsuranceSales_QoQ  \
0  ...                                 -0.594595   

   PolicyholderBenefitsAndClaimsIncurredNet_QoQ  PremiumsEarnedNet_QoQ  \
0                                     -0.011765               0.033463   

   ProvisionForLoanLossesExpensedAllowanceRecorded_QoQ  \
0                                          -1.126126     

   RealizedGainLossOnMarkToMarketOnCertainInstruments_QoQ  Revenues_QoQ  \
0                                          -0.442553           0.256018   

   StrategicDigitizationExpense_QoQ  \
0                               0.5   

   TotalRealizedGainLossRelatedToCertainInvestments_QoQ  \
0                                          -1.137681      

   VariableAnnuityNetDerivativesResultsAssociatedAmortizationIncomeExpense_QoQ  \
0                                                0.0                             

   VariableAnnuityNetDerivativesResultsGrossGainLoss_QoQ  
0                                           0.215686      

[1 rows x 47 columns]

In [140]:
print('Financial Features Captured for the QoQ percentage view:',len(GAAP_features['QoQ_pct'].columns))

Financial Features Captured for the QoQ percentage view: 47


In [141]:
GAAP_features['YoY_pct']

period_start_YoY period_end_YoY  \
0       2020-01-01     2021-06-30   

   AmortizationAssociatedWithRealizedGainLossOnCertainInvestments_YoY  \
0                                          -1.232558                    

   AmortizationOfDeferredGainOnBusinessSoldThroughReinsurance_YoY  \
0                                          -0.222222                

   BenefitsLossesAndExpenses_YoY  \
0                       0.083953   

   CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect_YoY  \
0                                          -0.662687                                                                    

   CashFlowHedgeReclassifiedToEarningsNet_YoY  \
0                                        -1.0   

   CommonStockIssuedForBenefitPlansAndExcessTaxBenefits_YoY  \
0                                           0.571429          

   ComprehensiveIncomeNetOfTax_YoY  \
0                        -1.228498   

   DebtAndEquitySecuritiesRealizedGainLoss_YoY  ...  \
0                                    -1.089655  ...   

   RepaymentAndMaturitiesOfMortgageLoansOnRealEstate_YoY  \
0                                           0.419463       

   RepaymentsOfLongTermDebt_YoY  Revenues_YoY  \
0                           1.0      0.173958   

   StrategicDigitizationExpense_YoY  \
0                          0.346154   

   SupplementalInformationForPropertyCasualtyInsuranceUnderwritersCurrentYearClaimsAndClaimsAdjustmentExpense_YoY  \
0                                            0.10907                                                                

   TotalRealizedGainLossRelatedToCertainInvestments_YoY  \
0                                           -1.22973      

   TransfersToAndFromSeparateAccountsNet_YoY  \
0                                  -2.060185   

   VariableAnnuityNetDerivativesResultsAssociatedAmortizationIncomeExpense_YoY  \
0                                          -0.058824                             

   VariableAnnuityNetDerivativesResultsGrossGainLoss_YoY  \
0                                           0.027273       

   WithdrawalsOfFixedAccountValuesIncludingFixedPortionOfVariable_YoY  
0                                          -0.002431                   

[1 rows x 97 columns]

In [142]:
print('Financial Features Captured for the YTD percentage view:',len(GAAP_features['YoY_pct'].columns))

Financial Features Captured for the YTD percentage view: 97


# Fiscal Instances View 
* The fiscal instance view is a pandas dataframe containing all fiscal instances disclosed within a filing.
* Each row represents a separate fiscal instant and includes the context_instant_date when the instance snapshot was taken. 
* Dataframe columns contain all fiscal instant features disclosed in a filing.
* Fiscal instant features that are missing from a particular context_instant_date will contain a value of NaN. 
* Rows are sorted by the context instant date.

**Scrolling to the far right the fiscal instance view also shows:**
 * **context_instant_days_diff** - The difference in days between each row's context instant date.
 * **period_end_date_days_diff** - The difference in days between context instant date and document period end date.
 * **days_from_dped** - The absolute difference in days between context instant date and document period end date.
 * **days_from_fyed** - The absolute difference in days between context instant date and the last fiscal year end date.

### Fiscal Instant View - Example Filing
**Fiscal Instances are currently captured for all fillings with 97.29% coverage.**

In [105]:
GAAP_features['gaap_FI']

concept_name context_instant_date  AccruedInvestmentIncomeReceivable  \
0                      2019-12-31                                NaN   
1                      2020-03-31                                NaN   
2                      2020-06-30                                NaN   
3                      2020-12-31                       1.217000e+09   
4                      2021-03-31                                NaN   
5                      2021-06-30                       1.215000e+09   
6                      2021-08-09                                NaN   

concept_name  AccumulatedOtherComprehensiveIncomeLossNetOfTax        Assets  \
0                                                         NaN           NaN   
1                                                         NaN           NaN   
2                                                         NaN           NaN   
3                                                9.021000e+09  3.683190e+11   
4                                                         NaN           NaN   
5                                                7.561000e+09  3.841280e+11   
6                                                         NaN           NaN   

concept_name  AvailableForSaleDebtSecuritiesAmortizedCostBasis  \
0                                                          NaN   
1                                                          NaN   
2                                                          NaN   
3                                                 1.030210e+11   
4                                                          NaN   
5                                                 1.055300e+11   
6                                                          NaN   

concept_name  AvailableForSaleSecuritiesDebtSecurities  \
0                                                  NaN   
1                                                  NaN   
2                                                  NaN   
3                                         1.211110e+11   
4                                                  NaN   
5                                         1.204520e+11   
6                                                  NaN   

concept_name  AvailableforsaleSecuritiesInUnrealizedLossPositionsQualitativeDisclosureNumberOfPositions1  \
0                                                           NaN                                            
1                                                           NaN                                            
2                                                           NaN                                            
3                                                           NaN                                            
4                                                           NaN                                            
5                                                        1353.0                                            
6                                                           NaN                                            

concept_name  CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents  \
0                                                  1.879000e+09               
1                                                           NaN               
2                                                  3.219000e+09               
3                                                  1.462000e+09               
4                                                           NaN               
5                                                  1.914000e+09               
6                                                           NaN               

concept_name  CollateralObtainedPercentOfFairValueSecuritiesLendingAgreementsDomestic  \
0                                                           NaN                         
1                                                           NaN                         
2                              

### Instances Disclosed in the Example Filing 
When considering the filing metadata, context_instant_date, days_from_dped, and days_from_fyed for the example filing we see the following fiscal instances disclosed in the example filing: 

**Quarter over Quarter snapshots are disclosed for the current quarter:**  
* DocumentPeriodEndDate: 2021-06-30
* QoQ 1: 2021-06-30 and 2020-06-30

**Quarter over Quarter snapshots are disclosed for the prior quarter:**  
* DocumentPeriodEndDate: 2021-06-30
* QoQ 2: 2021-03-31 and 2020-03-31 

**Year over year snapshots are disclosed for the Fiscal Year End Date:**
 * DocumentPeriodEndDate: 2021-06-30 
 * CurrentFiscalYearEndDate: --12-31 
 * Last Fiscal Year End: 2020-12-31
 * Fiscal YoY Instants: 2020-12-31 and 2019-12-31	
 
**Note:**

After closer inspection of the data it also appears that the filer disclosed EntityCommonStockSharesOutstanding as of 2021-08-09. 

In [114]:
metadata = GAAP_features['gaap_metadata'] 
print('CurrentFiscalYearEndDate:', metadata['CurrentFiscalYearEndDate'])
print('DocumentPeriodEndDate:', metadata['DocumentPeriodEndDate'])
print('DocumentFiscalPeriodFocus:', metadata['DocumentFiscalPeriodFocus'])

GAAP_features['gaap_FI'][['context_instant_date', 'context_instant_days_diff', 'days_from_dped', 'days_from_fyed']]

CurrentFiscalYearEndDate: --12-31
DocumentPeriodEndDate: 2021-06-30
DocumentFiscalPeriodFocus: Q2


concept_name context_instant_date context_instant_days_diff days_from_dped  \
0                      2019-12-31                    0 days       547 days   
1                      2020-03-31                   91 days       456 days   
2                      2020-06-30                   91 days       365 days   
3                      2020-12-31                  184 days       181 days   
4                      2021-03-31                   90 days        91 days   
5                      2021-06-30                   91 days         0 days   
6                      2021-08-09                   40 days        40 days   

concept_name days_from_fyed  
0                  366 days  
1                  275 days  
2                  184 days  
3                    0 days  
4                   90 days  
5                  181 days  
6                  221 days

In [126]:
print('\nReview of items disclosed on 2021-08-09:')

gfi = GAAP_features['gaap_FI']
gfi = gfi[gfi.context_instant_date == '2021-08-09'].T
gfi.columns = ['concept_value']

gfi[gfi.concept_value.isnull() == False]


Review of items disclosed on 2021-08-09:


concept_value
concept_name                                           
context_instant_date                2021-08-09 00:00:00
EntityCommonStockSharesOutstanding           10000000.0
context_instant_days_diff              40 days 00:00:00
period_end_date_days_diff              40 days 00:00:00
days_from_dped                         40 days 00:00:00
days_from_fyed                        221 days 00:00:00

# Matched Fiscal Instance Views

**The GaapFeatures library currently matches one type of fiscal instances for all filings:**
* FYED_to_DPED - Matched fiscal instance data for the prior fiscal year end and the document period end.  

 **Fiscal Year-End Date (FYED) to Document Period End Date (DPED):** 
 * Count: 78605 
 * Coverage: 95.91% 

In [145]:
GAAP_features['FYED_to_DPED']

concept_name context_instant_date  AccruedInvestmentIncomeReceivable  \
3                      2020-12-31                       1.217000e+09   
5                      2021-06-30                       1.215000e+09   

concept_name  AccumulatedOtherComprehensiveIncomeLossNetOfTax        Assets  \
3                                                9.021000e+09  3.683190e+11   
5                                                7.561000e+09  3.841280e+11   

concept_name  AvailableForSaleDebtSecuritiesAmortizedCostBasis  \
3                                                 1.030210e+11   
5                                                 1.055300e+11   

concept_name  AvailableForSaleSecuritiesDebtSecurities  \
3                                         1.211110e+11   
5                                         1.204520e+11   

concept_name  CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents  \
3                                                  1.462000e+09               
5                                                  1.914000e+09               

concept_name  CollateralPayableHeldForDerivativeInvestmentsCarryingValue  \
3                                                  2.970000e+09            
5                                                  4.384000e+09            

concept_name  CollateralPayableHeldForDerivativeInvestmentsFairValue  \
3                                                  2.970000e+09        
5                                                  4.384000e+09        

concept_name  CommonStockSharesAuthorized  ...  SecuritiesLoanedGross  \
3                              10000000.0  ...           4.665000e+09   
5                              10000000.0  ...           7.482000e+09   

concept_name  SecuritiesLoanedIncludingNotSubjectToMasterNettingArrangementAndAssetsOtherThanSecuritiesTransferred  \
3                                                   115000000.0                                                      
5                                                   228000000.0                                                      

concept_name  SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisCarryingValue  \
3                                                  3.130000e+09                    
5                                                  3.580000e+09                    

concept_name  SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisFairValue  \
3                                                  5.049000e+09                
5                                                  5.525000e+09                

concept_name  SecuritiesPledgedUnderSecuritiesLendingAgreementsFairValue  \
3                                                   112000000.0            
5                                                   222000000.0            

concept_name  SeparateAccountAssets  SeparateAccountsLiability  \
3                      1.679650e+11               1.679650e+11   
5                      1.787950e+11               1.787950e+11   

concept_name  StockholdersEquity  \
3                   2.504100e+10   
5                   2.408900e+10   

concept_name  TotalPayablesForCollateralOnInvestmentFairValue  \
3                                                8.131000e+09   
5                                                1.013100e+10   

concept_name  TradingSecuritiesDebt  
3                      4.442000e+09  
5                      4.175000e+09  

[2 rows x 92 columns]

In [146]:
print('Financial Features Captured for the FYED_to_DPED view:',len(GAAP_features['FYED_to_DPED'].columns))

Financial Features Captured for the FYED_to_DPED view: 92


# Percentage Change Instance Views 
**Percentage changes are calculated for all financial features disclosed in the FYED_to_DPED view.**

**Fiscal Year-End Date to Document Period End Date Percentages FYED_to_DPED_pct** 
* Count: 78605 
* Coverage: 95.91% 

In [147]:
GAAP_features['FYED_to_DPED_pct']

period_start_FYED_to_DPED period_end_FYED_to_DPED  \
0                2020-12-31              2021-06-30   

   AccruedInvestmentIncomeReceivable_FYED_to_DPED  \
0                                       -0.001643   

   AccumulatedOtherComprehensiveIncomeLossNetOfTax_FYED_to_DPED  \
0                                          -0.161845              

   Assets_FYED_to_DPED  \
0             0.042922   

   AvailableForSaleDebtSecuritiesAmortizedCostBasis_FYED_to_DPED  \
0                                           0.024354               

   AvailableForSaleSecuritiesDebtSecurities_FYED_to_DPED  \
0                                          -0.005441       

   CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents_FYED_to_DPED  \
0                                           0.309166                            

   CollateralPayableHeldForDerivativeInvestmentsCarryingValue_FYED_to_DPED  \
0                                           0.476094                         

   CollateralPayableHeldForDerivativeInvestmentsFairValue_FYED_to_DPED  ...  \
0                                           0.476094                    ...   

   SecuritiesLoanedGross_FYED_to_DPED  \
0                            0.603859   

   SecuritiesLoanedIncludingNotSubjectToMasterNettingArrangementAndAssetsOtherThanSecuritiesTransferred_FYED_to_DPED  \
0                                           0.982609                                                                   

   SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisCarryingValue_FYED_to_DPED  \
0                                            0.14377                                 

   SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisFairValue_FYED_to_DPED  \
0                                           0.094276                             

   SecuritiesPledgedUnderSecuritiesLendingAgreementsFairValue_FYED_to_DPED  \
0                                           0.982143                         

   SeparateAccountAssets_FYED_to_DPED  SeparateAccountsLiability_FYED_to_DPED  \
0                            0.064478                                0.064478   

   StockholdersEquity_FYED_to_DPED  \
0                        -0.038018   

   TotalPayablesForCollateralOnInvestmentFairValue_FYED_to_DPED  \
0                                           0.245972              

   TradingSecuritiesDebt_FYED_to_DPED  
0                           -0.060108  

[1 rows x 93 columns]

In [148]:
print('Financial Features Captured for the FYED_to_DPED percentage view:',len(GAAP_features['FYED_to_DPED_pct'].columns))

Financial Features Captured for the FYED_to_DPED percentage view: 93


# GAAP Percentage Features View
The GAAP percentage features view consolidates all filing metadata, QoQ_pct, YoY_pct, and FYED_to_DPED_pct data into a single consolidated view.
* Count: 79733 
* Coverage: 97.29% 

In [150]:
GAAP_features['gaap_pct_features']

FileName AmendmentFlag CurrentFiscalYearEndDate  \
0  726865_0000726865-21-000388         false                  --12-31   

  DocumentFiscalPeriodFocus EntityCentralIndexKey  \
0                        Q2            0000726865   

  EntityCurrentReportingStatus EntityInteractiveDataCurrent DocumentType  \
0                          Yes                          Yes         10-Q   

  DocumentQuarterlyReport DocumentPeriodEndDate  ...  \
0                    true            2021-06-30  ...   

  SecuritiesLoanedGross_FYED_to_DPED  \
0                           0.603859   

  SecuritiesLoanedIncludingNotSubjectToMasterNettingArrangementAndAssetsOtherThanSecuritiesTransferred_FYED_to_DPED  \
0                                           0.982609                                                                  

  SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisCarryingValue_FYED_to_DPED  \
0                                            0.14377                                

  SecuritiesPledgedForFederalHomeLoanBankOfIndianapolisFairValue_FYED_to_DPED  \
0                                           0.094276                            

  SecuritiesPledgedUnderSecuritiesLendingAgreementsFairValue_FYED_to_DPED  \
0                                           0.982143                        

  SeparateAccountAssets_FYED_to_DPED SeparateAccountsLiability_FYED_to_DPED  \
0                           0.064478                               0.064478   

  StockholdersEquity_FYED_to_DPED  \
0                       -0.038018   

  TotalPayablesForCollateralOnInvestmentFairValue_FYED_to_DPED  \
0                                           0.245972             

  TradingSecuritiesDebt_FYED_to_DPED  
0                          -0.060108  

[1 rows x 263 columns]

In [151]:
print('Financial Features Captured for the gaap_pct_features view:',len(GAAP_features['gaap_pct_features'].columns))

Financial Features Captured for the gaap_pct_features view: 263


# GAAP Full Data Repository
Data from each individual filing's gaap_pct_features view is also propagated into the GAAP Data Repository full datasets. The GAAP Data Repository comprises datasets containing one row per filing for all filings including:  

* GAAP_metadata_10Q_Full - A pandas dataframe with one row per filing containing all filing metadata. 
* GAAP_Pct_Chg_10Q_Full - A scipy sparse csr matrix containing one row per filing with sparse feature columns for all unique percentage change features across all filings (currently 220,992 financial features). 
* GAAP_Pct_Chg_10Q_Full_Feature_Names - An index of all feature names represented in GAAP_Pct_Chg_10Q_Full.

These files will eventually be incorporated into the daily models used predicting stock price changes. 

### Current GAAP_Pct_Chg_10Q_Full Features for Machine Learning 

### The current GAAP_Pct_Chg_10Q_Full file contains: 
* 79,733 filings 
* 220,992 financial features  

In [155]:
from Source.MonitorFilings.PersistedParameters import load_from_pickle

GAAP_Pct_Chg_10Q_Full = load_from_pickle(params.GAAP_pct_chg_repo_path)

GAAP_Pct_Chg_10Q_Full

<79733x220992 sparse array of type '<class 'numpy.float64'>'
	with 11695268 stored elements in Compressed Sparse Row format>

### The current GAAP_Pct_Chg_10Q_Full_Feature_Names file contains:
* 220,992 financial features names   

In [157]:
GAAP_Pct_Chg_10Q_Full_Feature_Names = load_from_pickle(params.GAAP_pct_chg_feature_names_path)

print('Feature Names:',len(GAAP_Pct_Chg_10Q_Full_Feature_Names))

Feature Names: 220992


In [166]:
print('Feature Names Sample\n')
list(GAAP_Pct_Chg_10Q_Full_Feature_Names.keys())[:50]

Feature Names Sample



['a2020labordaywildfireearningstestreserve_qoq',
 'a2023notesequityissuancecosts_qoq',
 'abandonedprojectcosts_qoq',
 'abandonedprojectcostsrecovered_qoq',
 'abandonedprojectsexpense_qoq',
 'abandonedwellcosts_qoq',
 'abandonmentexpenseofoilandgasproperties_qoq',
 'abandonmentpaymentstoacquireintangibleassets_qoq',
 'abatementofrent_qoq',
 'abnormalcostscovid19productionsuspension_qoq',
 'aboveandbelowmarketleasesamortizationexpenseincome_qoq',
 'aboveandbelowmarketleasesamortizationincome_qoq',
 'abovemarketcomponentofswapextensions_qoq',
 'abovemarketleaseassetamortization_qoq',
 'abovemarketleaseperiodincreasedecrease_qoq',
 'abovemarketleasesamortizationexpense_qoq',
 'academicrevenue_qoq',
 'acceleratedallocatedsharebasedcompensationexpense_qoq',
 'acceleratedamortizationofdeferredcharges_qoq',
 'acceleratedamortizationofintangibleassets_qoq',
 'acceleratedamortizationofintangibleliabilitiesfinitelived_qoq',
 'acceleratedamortizationofpatents_qoq',
 'acceleratedcompensationexpense

### The current GAAP_metadata_10Q_Full file contains:
* 79733 Filings 
* 28 columns of metadata for each filing  

In [170]:
metadata_full = load_from_pickle(params.GAAP_metadata_repo_path)
metadata_full

FileName AmendmentFlag CurrentFiscalYearEndDate  \
0      1593034_0001593034-19-000016         false                  --12-31   
1       315858_0000315858-20-000079         false                  --12-31   
2       832480_0001140361-21-017387         false                  --12-31   
3      1177702_0001564590-21-021349         false                  --12-31   
4      1769663_0001558370-22-008327         false                  --06-30   
...                             ...           ...                      ...   
79728  1596967_0001564590-20-034909         false                  --12-31   
79729    78890_0000078890-22-000426         false                  --12-31   
79730  1463172_0001463172-22-000326         false                  --12-31   
79731  1284450_0001213900-19-009166         false                  --12-31   
79732  1761312_0001558370-20-005437         false                  --12-31   

      DocumentFiscalPeriodFocus DocumentFiscalYearFocus EntityCentralIndexKey  \
0                            Q1                    2019            0001593034   
1                            Q2                    2020            0000315858   
2                            Q1                    2021            0000832480   
3                            Q1                    2021            0001177702   
4                            Q3                    2022            0001769663   
...                         ...                     ...                   ...   
79728                        Q2                    2020            0001596967   
79729                        Q3                    2022            0000078890   
79730                        Q3                    2022            0001463172   
79731                        Q1                    2019            0001284450   
79732                        Q1                    2020            0001761312   

      DocumentType DocumentQuarterlyReport DocumentPeriodEndDate  \
0             10-Q                    None            2019-03-31   
1             10-Q                    true            2020-06-30   
2             10-Q                    true            2021-03-31   
3             10-Q                    true            2021-03-31   
4             10-Q                    true            2022-03-31   
...            ...                     ...                   ...   
79728         10-Q                    true            2020-06-30   
79729         10-Q                    true            2022-09-30   
79730         10-Q                    true            2022-09-30   
79731         10-Q                    None            2019-03-31   
79732         10-Q                    None            2020-03-31   

      DocumentTransitionReport  ... CityAreaCode LocalPhoneNumber  \
0                         None  ...         None             None   
1                        false  ...          954         940-4900   
2                        false  ...          217         323-6300   
3                        false  ...          770         232-5067   
4                        false  ...          518         730-3025   
...                        ...  ...          ...              ...   
79728                    false  ...          212         883-3800   
79729                    false  ...          804         289-9600   
79730                    false  ...          415         418-7506   
79731                     None  ...         None             None   
79732                     None  ...         None             None   

      EntityCurrentReportingStatus EntityInteractiveDataCurrent  \
0                             None                         None   
1                              Yes                          Yes   
2                              Yes                          Yes   
3                              Yes                          Yes   
4                              Yes                          Yes   
...                            ...                          ...   
79

### GAAP_metadata_10Q_Full Column Names:

In [171]:
metadata_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79733 entries, 0 to 79732
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype 
---  ------                               --------------  ----- 
 0   FileName                             79733 non-null  object
 1   AmendmentFlag                        79733 non-null  object
 2   CurrentFiscalYearEndDate             79733 non-null  object
 3   DocumentFiscalPeriodFocus            79733 non-null  object
 4   DocumentFiscalYearFocus              79732 non-null  object
 5   EntityCentralIndexKey                79733 non-null  object
 6   DocumentType                         79733 non-null  object
 7   DocumentQuarterlyReport              61290 non-null  object
 8   DocumentPeriodEndDate                79733 non-null  object
 9   DocumentTransitionReport             61088 non-null  object
 10  EntityFileNumber                     65203 non-null  object
 11  EntityRegistrantName                 7950